create extension if not exists pgcrypto;

create table if not exists public.users (
  telegram_user_id text primary key,
  username text,
  first_name text,
  last_name text,
  language_code text,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.business_connections (
  connection_id text primary key,
  owner_user_id text not null references public.users(telegram_user_id) on delete cascade,
  owner_chat_id text not null,
  is_enabled boolean not null default true,
  can_reply boolean not null default false,
  rights_json jsonb,
  created_at_unix bigint not null,
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_business_connections_owner_chat_id
  on public.business_connections(owner_chat_id);

create table if not exists public.chats (
  connection_id text not null references public.business_connections(connection_id) on delete cascade,
  chat_id text not null,
  type text,
  title text,
  username text,
  first_name text,
  last_name text,
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (connection_id, chat_id)
);

create table if not exists public.archived_messages (
  id bigint generated by default as identity primary key,
  connection_id text not null references public.business_connections(connection_id) on delete cascade,
  chat_id text not null,
  message_id bigint not null,
  sender_user_id text,
  sender_name text,
  direction text not null default 'incoming',
  sent_at_unix bigint,
  text_content text,
  caption_content text,
  message_kind text not null,
  raw_json jsonb not null,
  was_deleted boolean not null default false,
  deleted_at_unix bigint,
  created_at timestamptz not null default timezone('utc', now()),
  unique(connection_id, chat_id, message_id)
);

create index if not exists idx_archived_messages_lookup
  on public.archived_messages(connection_id, chat_id, message_id);

create index if not exists idx_archived_messages_connection_created
  on public.archived_messages(connection_id, created_at desc);

create table if not exists public.message_media (
  id bigint generated by default as identity primary key,
  connection_id text not null references public.business_connections(connection_id) on delete cascade,
  chat_id text not null,
  message_id bigint not null,
  media_type text not null,
  file_id text,
  file_unique_id text,
  file_name text,
  mime_type text,
  file_size bigint,
  local_path text,
  telegram_file_path text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_message_media_lookup
  on public.message_media(connection_id, chat_id, message_id);

create table if not exists public.message_edits (
  id bigint generated by default as identity primary key,
  connection_id text not null references public.business_connections(connection_id) on delete cascade,
  chat_id text not null,
  message_id bigint not null,
  old_text text,
  new_text text,
  old_caption text,
  new_caption text,
  edited_at_unix bigint not null,
  raw_json jsonb not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_message_edits_lookup
  on public.message_edits(connection_id, chat_id, message_id);

create table if not exists public.delete_events (
  id bigint generated by default as identity primary key,
  connection_id text not null references public.business_connections(connection_id) on delete cascade,
  chat_id text not null,
  message_id bigint not null,
  deleted_at_unix bigint not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_delete_events_lookup
  on public.delete_events(connection_id, chat_id, message_id);

alter table public.users enable row level security;
alter table public.business_connections enable row level security;
alter table public.chats enable row level security;
alter table public.archived_messages enable row level security;
alter table public.message_media enable row level security;
alter table public.message_edits enable row level security;
alter table public.delete_events enable row level security;

-- Service role bypasses RLS. Keep anon access disabled unless you add explicit policies later.
